apiVersion: v1
kind: Service
metadata:
  labels:
    app: pure-ftpd
  name: pure-ftpd
  namespace: myproject
spec:
  clusterIP: None
  ports:
    - name: 21-tcp
      port: 21
      protocol: TCP
      targetPort: 21
    - name: 30000-tcp
      port: 30000
      protocol: TCP
      targetPort: 30000
    - name: 30001-tcp
      port: 30001
      protocol: TCP
      targetPort: 30001
    - name: 30002-tcp
      port: 30002
      protocol: TCP
      targetPort: 30002
    - name: 30003-tcp
      port: 30003
      protocol: TCP
      targetPort: 30003
    - name: 30004-tcp
      port: 30004
      protocol: TCP
      targetPort: 30004
    - name: 30005-tcp
      port: 30005
      protocol: TCP
      targetPort: 30005
    - name: 30006-tcp
      port: 30006
      protocol: TCP
      targetPort: 30006
    - name: 30007-tcp
      port: 30007
      protocol: TCP
      targetPort: 30007
    - name: 30008-tcp
      port: 30008
      protocol: TCP
      targetPort: 30008
    - name: 30009-tcp
      port: 30009
      protocol: TCP
      targetPort: 30009
  selector:
    deploymentconfig: pure-ftpd
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
